### ISSUE TITLE
raw_high_lat crashes in electrodynamics routine

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#101]
After resolving Issue #100, another bug has appeared. Parallel simulations with IPE standalone crash within an electrodynamics routine. From a comment from #100 by @IonospherePlasmasphereElectrodynamics , 
" found out my previous parallel 464prcs run had a problem.
now both parallel 2 and 464 prcs runs crashed at the same, new location:

https://github.com/SWPC-IPE/WAM-IPE/blob/raw_high_lat/IPELIB/src/eldyn/get_efield90km.f#L292

sub-get_e:NH!STOP! INVALID 1 0 1 250 6461200. 1.1770907E-43 3.4906585E-02 "

The serial simulation does not crash here suggesting that the issue is linked to the parallelization.

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
it is very strange that neither of these values (r, coslam_m, d_phi_m ) does meet the if conditions (https://github.com/SWPC-IPE/WAM-IPE/blob/raw_high_lat/IPELIB/src/eldyn/get_efield90km.f#L267) that caused the code to stop, but it is trapped here somehow.
 
sub-get_e:NH!STOP! INVALID:lp=           1  mp=           1  mype=           1
 r=   6461200.      coslam_m=  6.7262326E-44 d_phi_m=  3.4906585E-02

**Comment by joeschoonover** [comment]
coslam_m is close enough to zero that this would cause the conditional to be satisfied

**Comment by joeschoonover** [comment]
If I recall correctly, coslam_m is calculated using the plasma_grid_3d field. If so, we should check to make sure that plasma_grid_3d is read in correctly. Perhaps running in serial, and printing to screen the max and min values of plasma_grid_3d, then run in parallel, and have the master rank do the same just after reading plasma_grid_3d from file

**Comment by joeschoonover** [comment]
correction, coslam_m is calculated using plasma_grid_GL

**Comment by joeschoonover** [comment]
plasma_grid_GL for a serial and parallel-464 run both have the same plasma_grid_GL values. We should print out coslam_m values next to compare.

**Comment by joeschoonover** [comment]
parallel 464 run does not make it past io_plasma_bin still

**Comment by joeschoonover** [comment]
Currently, the crash statement within the electrodynamics routines is : 
```
SMS: Abort Message=get_efield90km_sms.f90:122
```

**Comment by joeschoonover** [comment]
The corresponding line in the pre-interpeted `get_efield90km.f90` had a stop statement inserted just after reading plasma_grid_GL -- I think I had accidentally committed that recently. It is now removed

**Comment by joeschoonover** [comment]
After removing that stop statement, it looks like IPE standalone is running now.

**Comment by joeschoonover** [comment]
@IonospherePlasmasphereElectrodynamics , if you verify that the tip of raw_high_lat is running without crashing, we'll close this issue

**Comment by IonospherePlasmasphereElectrodynamics** [comment]
for validation, I did 3 standalone IPE tests: (1) serial; (2) parallel 1 (3) parallel 464. all 3 runs have finished successfully (duration=600s).

(2) and (3) have mostly b4b exactness, except for ipe_grid plasma_params... files at time step=300 and 600.

(1) and (2) have mostly b4b exactness, except for ipe_grid plasma_params... files at time step=300 and 600, fort.2007(theta90_rad), fort.2009(ed2_90), fort.2012(vexbe).

calculating ed2_90 involves coslam_m that was discussed previously. these differences need some further investigations. 

it just occurred to me that the module parameter names, ylatm, ylonm  in module_efield.f may need changing, because both WAM and IPE use the same efield module within which the same module parameters are used, although this may not be the real cause of the differences.

**Comment by joeschoonover** [comment]
@IonospherePlasmasphereElectrodynamics , do your runs also get past the electrodynamics routines ? If so, we should close this issue.

To get b4b exactness, the -fp-model strict needs to be turned on. I suspect that the solutions are very close.
