### ISSUE TITLE
Constant changes to compset scripts when new runs are needed

### ISSUE THREAD

**Issue by schoonovernumerics** [SWPC-IPE/WAM-IPE#12]
The current organization of the compset scripts is a mess. To perform different runs, we are commenting out other's code and adding new code. This practice will contribute towards making these scripts unmanageable. A good solution would be to have a directory structure, where each configuration can be set up and left alone (for the most part). 

Under the main directory, I propose the following structure : 
configurations/ (new directory)
configurations/YYYYMMDDHH_simtime
configurations/YYYYMMDDHH_simtime/grid_nlonXnlat

Underneath the final subdirectory, the compset scripts and any IPE configuration scripts should be placed there.

**Comment by akubaryk** [comment]
New run scripts are in `scripts/compsets/`, started in earnest from `85aaecb` and continually updated, but there still needs to be additional documentation and testing with our user-base before this issue is closed. We also need to finalize a plan for the initial condition structure and put our main test cases into a single location for archival.
