### ISSUE TITLE
Cycling not functioning on raw_high_lat

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#123]
When using the `submit.sh` script on the raw_high_lat branch, we currently cannot get restarts to be resubmitted to the job queue automatically. For example,

```
./submit.sh march2013_regression.config 1 2
```
does not give one cold start run followed by one restart run. This is observed, even after removing the RESTART environment variable from the config file. I thought I had carried over the appropriate changes from the development branch, but I guess something is missing.

**Comment by joeschoonover** [comment]
I'm double checking that this is still an issue on the raw_high_lat branch

**Comment by joeschoonover** [comment]
It appears that this is an issue only with the WAM standalone runs.

**Comment by twfang** [comment]
When trying to run standalone WAM on raw_high_lat branch, WAM won't restart due to a missing file called "wam_ipe_rst_rd". See the message below. 

checking for ROTDIR: /scratch4/NCEPDEV/stmp3/Tzu-Wei.Fang/wam_standalone
checking for RESTARTDIR: /scratch4/NCEPDEV/stmp3/Tzu-Wei.Fang/wam_standalone/restart_directory
checking for atmospheric/surface restart files in RESTARTDIR /scratch4/NCEPDEV/stmp3/Tzu-Wei.Fang/wam_standalone/restart_directory
ls: cannot access /scratch4/NCEPDEV/stmp3/Tzu-Wei.Fang/wam_standalone/restart_directory/wam_ipe_rst_rd: No such file or directory
   restart file /scratch4/NCEPDEV/stmp3/Tzu-Wei.Fang/wam_standalone/restart_directory/wam_ipe_rst_rd not found! exiting.

**Comment by joeschoonover** [comment]
When WAM is not coupled to IPE, we need to remove the check for searching for the wam_ipe_rst_rd file.

**Comment by joeschoonover** [comment]
Resolved. See hash id 77cf3bc882841da21d01c922a4ae293ef227418e for details. Update your local version of raw_high_lat to use the fixed version
