### ISSUE TITLE
Restarts runs crash a few iterations in

### ISSUE THREAD

**Issue by schoonovernumerics** [SWPC-IPE/WAM-IPE#16]
RC0.0.3 is producing restarts that crash after a few iterations of running, with solutions resulting in NaN's.

**Comment by schoonovernumerics** [comment]
The crash happens a few days (in simulation time) after the restart run begins. When it crashes, a segmentation fault occurs : 
![screenshot from 2017-08-31 14-09-27](https://user-images.githubusercontent.com/11430768/29943273-2e469cb2-8e56-11e7-912e-c54837ca7bf3.png)

**Comment by schoonovernumerics** [comment]
Additionally, we see an error that looks like its coming from WAM : 
pcorr pdryini pdryg                      NaN   98.1970363405300
[0]                      NaN
[3] forrtl: severe (174): SIGSEGV, segmentation fault occurred

**Comment by schoonovernumerics** [comment]
We need to run another restart starting with the last set of output from the crashed run. All of the output seems normal.

**Comment by twfang** [comment]
The issue is related to the dimension of F107_KP_SIZE set in the compsets. 
The dimension of  F107_KP_SIZE was set to 56, which led the model to crash after 7 days. To solve the issue, F107_KP_SIZE has been modified to a larger number (4800) for now, which will allow us to run the model for at least 600 days. 

Solution: set "export F107_KP_SIZE=4800" in compsets.
