### ISSUE TITLE
Update WAM Startup Files

### ISSUE THREAD

**Issue by twfang** [SWPC-IPE/WAM-IPE#178]
We need to update WAM initial conditions to reflect changes in WAM physics.

**Comment by twfang** [comment]
A 5-day coupled WAM-IPE with latest initial conditions has been submitted.

**Comment by ZhuxiaoLi66** [comment]
an annual run is running with fixed f107(120) and kp(3) and all the updates for the new IC files.  Actually, the new restart features will very slightly change the values of output.

**Comment by ZhuxiaoLi66** [comment]
The output folder of annual run with fixed F107(120) and Kp(3) is:  
/scratch3/NCEPDEV/swpc/scrub/Zhuxiao.Li/PTMP/v3_fix_0320_75day_ann

The one of the annual run with all variable drivers in is: 
/scratch3/NCEPDEV/swpc/scrub/Zhuxiao.Li/PTMP/v3_swin_0320_45day_ann_new 

Both runs begin at 20130320 and have output of 225 days due to the lack of the Aurora driver data in 2014, will change the start date and get the whole year effective output and get some hourly output (now is 6 hrly output).
