### ISSUE TITLE
Clean up : Source code consolidation and cleanup under neutral directory

### ISSUE THREAD

**Issue by joeschoonover** [SWPC-IPE/WAM-IPE#52]
As with other directories within the IPELIB source code, there are many modules that define only one routine. To help improve readability and make code management easier, neutral routines should be examined and consolidated in fewer modules. Tasks should include : 

* List all neutral routines and define their purpose
* Determine what source code is still in use
* Consolidate used routines under fewer modules and reduce code redundancies.

During this code cleanup process, source code should conform to code formatting standards.

**Comment by joeschoonover** [comment]
We have started a document to describe what we're doing : 
https://docs.google.com/a/noaa.gov/document/d/1lC1JX_mQve_UvBWpRecLZPE67tICllLKXhEV_oPkp68/edit?usp=sharing

**Comment by gmillward** [comment]
Working on the neutral module - confirmed that at high altitudes on the flux-tubes, neutral O, O2 and N2 densities can go to zero because the values get smaller than the precision of the machine (roughly 1.0e-45).
Not clear whether this issue affects the IPE solver, but it easily could be a problem. 

Fix is to provide a lower boundary on such densities - to make sure no values can be exactly zero.

**Comment by joeschoonover** [comment]
Rolling this issue into the IPELIB refactoring project
