### ISSUE TITLE
WAM Physics : High level heating related to vertical eddy mixing

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [SWPC-IPE/WAM-IPE#76]
We found that the WAM neutral temperature become too warm (about 100 deg from MSIS at higher levels), after we revised (adding idea_tracer_eddy) the vertical eddy mixing physics code (idea_tracer.f) to get a better O/N2 ratio at higher levels.  Now we are trying to improve the physics in idea_solar_heating.f and then adjust the Joule heating related parameters in idea_ion.f.

**Comment by ZhuxiaoLi0113** [comment]
After did many experiments on tuning idea_solar_heating.f and idea_ion.f to get rid of the higher global mean temp., we changed the strategy to modify the Joule Heating factor to decrease the global mean temp. since it will lose the agreement with latitude structure of both T and O/N2 in all season.  We plan to scale the solar heating (idea_dissipation.f) directly.

**Comment by timfullerrowell** [comment]
Here is a summary as I see it, please check you agree:

Goal:
a) To be reasonably close to NRLMSIS empirical model for global mean composition (O, O2, and N2) and temperature profiles each month through the year (for IPE loss processes).
b) To be reasonably close to the latitude structure of temperature and composition (mean mass) each month through the year (for IPE loss processes).

For a) we originally had too much atomic oxygen and not enough molecular oxygen and nitrogen, so we introduced an eddy mixing for species Kt. This worked well and I think is what is in the development version of WAM-IPE.

For b) we scaled Joule heating amplitude and added a seasonal variation, which increased the factor in winter relative to summer. Again, this worked well, but not sure if this in in the development version.

Since then:

1. Rashid realized that the way we are treating the Sun-Earth distance does not capture the seasonal changes for wavelengths in the solar spectrum that do not correlate with F10.7 one-to-one. So we divided the F10.7 by eccentricity (Sun-Earth distance) calculated the flux in each spectral band, then multiplied by eccentricity. Since this changes solar heating and dissociation in WAM it produced some significant changes.  
2. We increased CO2 concentration to currently observed values.

This requires retuning of the a) and b) above.

**Comment by ZhuxiaoLi0113** [comment]
https://drive.google.com/drive/u/0/folders/145xUFLSGomdkVpyEhYjcWZ13hcsFMO-X
The plots are the output from the WAM run with JouleHeating factoring + Vertical Eddy diffusion + new solar heating feature.

**Comment by ZhuxiaoLi0113** [comment]
https://drive.google.com/open?id=1azXviJ5zPKiNxotgB_1az4pMFnXbcOq2

The plots are by the output from the WAM run based on the physics schemes in above run plus the new annual CO2 (400) and the over adjusted Joule Heating factor instead the original one. 

The current base run is 
https://drive.google.com/drive/u/0/folders/145xUFLSGomdkVpyEhYjcWZ13hcsFMO-X

**Comment by ZhuxiaoLi0113** [comment]
analyzing the output and trying to make some more clear benchmark runs.

**Comment by ZhuxiaoLi66** [comment]
finished the benchmark runs and slightly revised the Joule Heating Factors. Will send the whole arranged and analyzed results to Tim and Rashid later. the good news is that Rashid is back to home from hospital and seems want to give input to this work again.

**Comment by ZhuxiaoLi66** [comment]
The new tweak on Joule Heating factor looks encouraging.  The plots are in 
https://drive.google.com/drive/u/0/folders/13CnNOsXrKMtdriVQum2ltbNryjJdCtaa

The whole folder for recent results is:
https://drive.google.com/drive/u/0/folders/0B7yKl_CH-n2_TEw0MnZQNVl3SW8

**Comment by joeschoonover** [comment]
Duplicated in #180
